sensor_list:
  - wheel_odometry
  - imu1
  
sensor_properties:
  wheel_odometry:
    sensor_topic: "/husky_velocity_controller/odom"
    sensor_type: "odometry"
    measurements: [ false  , false,   false,
                    false  , false,   false,
                    true , true,  false,
                    false , false,  true,
                    false , false,  false]

  imu1:
    sensor_topic: "/imu/data"
    sensor_type: "imu"
    measurements: [ false , false , false,
                    false , false , false,
                    false , false , false,
                    false , false , true,
                    true  , true  , false]

  imu2:
    sensor_topic: "/zed_camera/imu"
    sensor_type: "imu"
    measurements: [ false , false , false,
                    false , false , false,
                    false , false , false,
                    false , false , true,
                    true  , true  , false]
    
process_noise_covariance: [ 1e-3  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,
                            0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3]

initial_covariance: [ 1e-3  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3,  0.0,
                      0.0  ,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-3]



    